"""Typed input/output models for the Intelligence Engine."""

from intelligence.models.enums import (
    ALL_CORE_SCHEMES,
    Factor,
    INCOME_GENERATING_SCHEMES,
    INCOME_GROUP_NAME,
    MatchStatus,
    OverallStatus,
    PartnerStatus,
    Purpose,
    SCHEME_PRIORITY,
    SC_COMMUNITY,
    VerificationStatus,
    Verdict,
)
from intelligence.models.profile import (
    ENTITY_TYPE_ALIASES,
    ENTITY_TYPE_VALUES,
    GENERAL_NON_SC,
    SC_COMMUNITY_CANONICAL,
    ApplicantProfile,
)
from intelligence.models.requirement import Location, RecommendationRequest, Requirement
from intelligence.models.result import (
    ActivityMatchResult,
    ConditionalResolution,
    EducationFitResult,
    EligibilityResult,
    EngineMetadata,
    ExcludedScheme,
    FactorScore,
    FinancialConstraint,
    FinancialFitResult,
    MissingFieldEntry,
    PartnerFitResult,
    RecommendationResponse,
    RequestSummary,
    RuleResult,
    SchemeRecommendation,
    SourceRef,
)

__all__ = [
    "ALL_CORE_SCHEMES",
    "ENTITY_TYPE_ALIASES",
    "ENTITY_TYPE_VALUES",
    "Factor",
    "INCOME_GENERATING_SCHEMES",
    "INCOME_GROUP_NAME",
    "MatchStatus",
    "OverallStatus",
    "PartnerStatus",
    "Purpose",
    "SCHEME_PRIORITY",
    "SC_COMMUNITY",
    "SC_COMMUNITY_CANONICAL",
    "GENERAL_NON_SC",
    "VerificationStatus",
    "Verdict",
    "ApplicantProfile",
    "Location",
    "RecommendationRequest",
    "Requirement",
    "ActivityMatchResult",
    "ConditionalResolution",
    "EducationFitResult",
    "EligibilityResult",
    "EngineMetadata",
    "ExcludedScheme",
    "FactorScore",
    "FinancialConstraint",
    "FinancialFitResult",
    "MissingFieldEntry",
    "PartnerFitResult",
    "RecommendationResponse",
    "RequestSummary",
    "RuleResult",
    "SchemeRecommendation",
    "SourceRef",
]