"""Stable i18n reason keys (M2 §15).

These are the ONLY explanation identifiers the engine emits. The frontend/LLM
layer localizes them later (M0 B10: D3 owns EN/HI/TE strings). Every key maps
to a real engine fact; the explanation generator never emits free-form text.
"""

# ----------------------------------------------------------------- eligibility
COMMUNITY_MATCH = "COMMUNITY_MATCH"
COMMUNITY_MISMATCH = "COMMUNITY_MISMATCH"
MISSING_COMMUNITY = "MISSING_COMMUNITY"

INCOME_WITHIN_LIMIT = "INCOME_WITHIN_LIMIT"
INCOME_EXCEEDS_LIMIT = "INCOME_EXCEEDS_LIMIT"
MISSING_ANNUAL_INCOME = "MISSING_ANNUAL_INCOME"

CASTE_CERTIFICATE_EXISTS = "CASTE_CERTIFICATE_EXISTS"
CASTE_CERTIFICATE_MISSING = "CASTE_CERTIFICATE_MISSING"
MISSING_CASTE_CERTIFICATE = "MISSING_CASTE_CERTIFICATE"

ENTITY_TYPE_ALLOWED = "ENTITY_TYPE_ALLOWED"
ENTITY_TYPE_NOT_ALLOWED = "ENTITY_TYPE_NOT_ALLOWED"
MISSING_ENTITY_TYPE = "MISSING_ENTITY_TYPE"

RULE_PASS = "RULE_PASS"
RULE_FAIL = "RULE_FAIL"

# ------------------------------------------------------------------------- activity
ACTIVITY_MATCH = "ACTIVITY_MATCH"
ACTIVITY_NO_MATCH = "ACTIVITY_NO_MATCH"
ACTIVITY_UNSUPPORTED = "ACTIVITY_UNSUPPORTED"
ACTIVITY_UNVERIFIED = "ACTIVITY_UNVERIFIED"
MISSING_ACTIVITY = "MISSING_ACTIVITY"

# ------------------------------------------------------------------------- financial
PROJECT_COST_WITHIN_BOUNDS = "PROJECT_COST_WITHIN_BOUNDS"
PROJECT_COST_BELOW_MIN = "PROJECT_COST_BELOW_MIN"
PROJECT_COST_ABOVE_MAX = "PROJECT_COST_ABOVE_MAX"
MISSING_PROJECT_COST = "MISSING_PROJECT_COST"
LOAN_WITHIN_LIMIT = "LOAN_WITHIN_LIMIT"
LOAN_EXCEEDS_MAX = "LOAN_EXCEEDS_MAX"
LOAN_BELOW_MIN = "LOAN_BELOW_MIN"
MISSING_LOAN_AMOUNT = "MISSING_LOAN_AMOUNT"
FINANCIAL_OK = "FINANCIAL_OK"
FINANCIAL_UNKNOWN = "FINANCIAL_UNKNOWN"
ELS_CAP_APPLIED = "ELS_CAP_APPLIED"
MISSING_COURSE_FEE = "MISSING_COURSE_FEE"
FINANCIAL_AMOUNT_EXCEEDS_LIMIT = "FINANCIAL_AMOUNT_EXCEEDS_LIMIT"
FINANCIAL_AMOUNT_WITHIN_LIMIT = "FINANCIAL_AMOUNT_WITHIN_LIMIT"
CONDITIONAL_VALUE_UNKNOWN = "CONDITIONAL_VALUE_UNKNOWN"

# ------------------------------------------------------------------------- education
COURSE_COVERED = "COURSE_COVERED"
COURSE_NOT_COVERED = "COURSE_NOT_COVERED"
COURSE_COVERAGE_UNKNOWN = "COURSE_COVERAGE_UNKNOWN"
MISSING_COURSE = "MISSING_COURSE"

# ------------------------------------------------------------------------- partner
PARTNER_DATA_UNAVAILABLE = "PARTNER_DATA_UNAVAILABLE"

# ------------------------------------------------------------------------- overall
NO_MATCHING_SCHEME = "NO_MATCHING_SCHEME"
INSUFFICIENT_INFORMATION = "INSUFFICIENT_INFORMATION"
UNSUPPORTED_ACTIVITY = "UNSUPPORTED_ACTIVITY"

# ------------------------------------------------------------------- warnings
DERIVED_VALUE_IN_USE = "DERIVED_VALUE_IN_USE"
CONFLICTED_SOURCE_IN_USE = "CONFLICTED_SOURCE_IN_USE"