"""initial schema

Revision ID: 91339c116059
Revises: 
Create Date: 2026-09-08 17:43:55.800860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '91339c116059'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('sub_sector', sa.String(length=100), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('authority', sa.String(length=200), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_source_type'), ['source_type'], unique=False)

    op.create_table('els_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('partner_type', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index('ix_partners_lat_lng', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_partners_partner_id'), ['partner_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_partners_status'), ['status'], unique=False)

    op.create_table('schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scheme_type', sa.String(length=60), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=True),
    sa.Column('project_cost_min', sa.Float(), nullable=True),
    sa.Column('project_cost_max', sa.Float(), nullable=True),
    sa.Column('max_loan_amount', sa.Float(), nullable=True),
    sa.Column('financing_percentage', sa.Float(), nullable=True),
    sa.Column('nsfdc_interest_rate', sa.Float(), nullable=True),
    sa.Column('beneficiary_interest_rate', sa.Float(), nullable=True),
    sa.Column('repayment_period_months', sa.Integer(), nullable=True),
    sa.Column('moratorium_period_months', sa.Integer(), nullable=True),
    sa.Column('installment_frequency', sa.String(length=40), nullable=True),
    sa.Column('target_group', sa.String(length=200), nullable=True),
    sa.Column('application_mode', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schemes_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_schemes_scheme_id'), ['scheme_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_schemes_status'), ['status'], unique=False)

    op.create_table('application_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_requirements_scheme_id'), ['scheme_id'], unique=False)

    op.create_table('eligibility_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=80), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eligibility_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eligibility_rules_scheme_id'), ['scheme_id'], unique=False)

    op.create_table('partner_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('sanctioned_amount', sa.Float(), nullable=True),
    sa.Column('disbursed_amount', sa.Float(), nullable=True),
    sa.Column('utilization_percentage', sa.Float(), nullable=True),
    sa.Column('beneficiary_count', sa.Integer(), nullable=True),
    sa.Column('pending_amount', sa.Float(), nullable=True),
    sa.Column('npa_percentage', sa.Float(), nullable=True),
    sa.Column('overdue_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_performance_partner_id'), ['partner_id'], unique=False)

    op.create_table('scheme_partner_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('authorization_status', sa.String(length=20), nullable=False),
    sa.Column('geographic_scope', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme_id', 'partner_id', name='uq_scheme_partner')
    )
    with op.batch_alter_table('scheme_partner_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheme_partner_mapping_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheme_partner_mapping_scheme_id'), ['scheme_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheme_partner_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheme_partner_mapping_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_scheme_partner_mapping_partner_id'))

    op.drop_table('scheme_partner_mapping')
    with op.batch_alter_table('partner_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_performance_partner_id'))

    op.drop_table('partner_performance')
    with op.batch_alter_table('eligibility_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eligibility_rules_scheme_id'))

    op.drop_table('eligibility_rules')
    with op.batch_alter_table('application_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_requirements_scheme_id'))

    op.drop_table('application_requirements')
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schemes_status'))
        batch_op.drop_index(batch_op.f('ix_schemes_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_schemes_purpose'))

    op.drop_table('schemes')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_status'))
        batch_op.drop_index(batch_op.f('ix_partners_partner_id'))
        batch_op.drop_index('ix_partners_lat_lng')

    op.drop_table('partners')
    op.drop_table('els_courses')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_source_type'))

    op.drop_table('sources')
    op.drop_table('activities')
    # ### end Alembic commands ###
